### ISSUE TITLE
Use tilesheet API to import current set of tiles

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/ftb-rs#3]
The tilesheets extension, as of recently, provides an API to get the list of tiles for a given tilesheet. This program should be updated to fetch the list of tiles via the API instead of manually importing them via `import.txt`.

**Comment by retep998** [comment]
Rewrote issue because your original issue was dumb.

**Comment by elifoster** [comment]
Yes.

**Comment by xbony2** [comment]
@retep998 this can also be closed

**Comment by retep998** [comment]
Yes.
