### ISSUE TITLE
Easily customizable sizes

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/ftb-rs#4]
Right now, in order to use different sizes than `16,32` we have to modify the actual source files, which is annoying. We should be able to specify a list of sizes in the CLI args.

**Comment by retep998** [comment]
What I will do is if the program doesn't see an existing tilesheet, it'll then ask you what sizes you want.

**Comment by xbony2** [comment]
@retep998 this can be closed, as you have done just that

**Comment by retep998** [comment]
Yes.
